name: Deploy prod
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for testing
        run: docker build -t andqnguyen/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true andqnguyen/react-test npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #- name: Login to Docker
      #  run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build Docker image for deployment
      #  run: docker build -t andqnguyen/react-prod -f Dockerfile .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-904233091350
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip